services:
  php:
    build:
      target: dev
    image: fizzbuzz-api:dev
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      APP_ENV: dev
    volumes: !override
      - .:/app
    tmpfs: !reset []
    read_only: false

  db:
    ports:
      - "${DB_PORT:-3307}:3306"
